name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.8.2-alpine-build
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: make test
        continue-on-error: true
      - name: Build
        run: make
      - name: Build release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mkdir crash-${{github.ref_name}}
          cp bin/crash README.md LICENSE crash-${{github.ref_name}}/
          tar czpf crash-${{github.ref_name}}.tar.gz crash-${{github.ref_name}}
      - name: Publish release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            crash-${{github.ref_name}}.tar.gz
